/**
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

Solution: Bit manipulation.
*/

public class Solution {
    public char findTheDifference(String s, String t) {
        char[] sChars = s.toCharArray(); 
        char[] tChars = t.toCharArray(); 
        if (sChars.length == 0) {
            return tChars[0]; 
        }
        char res = sChars[0]; 
        for (int i = 1; i < sChars.length; i++) {
            res ^= sChars[i]; 
        }
        for (int j = 0; j < tChars.length; j++) {
            res ^= tChars[j]; 
        }
        return res; 
    }
}